#!/bin/bash
# http://www.dest-unreach.org/socat/doc/socat-ttyovertcp.txt
# EXAMPLE FOR REMOTE TTY (TTY OVER TCP) USING SOCAT
# 
# You have a host with some serial device like a modem or a bluetooth interface
# (modem server)
# You want to make use of this device on a different host. (client)
# 
# 1) on the modem server start a process that accepts network connections and
# links them with the serial device /dev/tty0:
# 
# $ socat tcp-l:54321,reuseaddr,fork file:/dev/tty0,nonblock,waitlock=/var/run/tty0.lock
# 
# 2) on the client start a process that creates a pseudo tty and links it with a
# tcp connection to the modem server:
# 
# $ socat pty,link=$HOME/dev/vmodem0,waitslave tcp:modem-server:54321
#  socat  FILE:/dev/ttyUSB0,nonblock,b9600,raw tcp:localhost:4161 

# 
# This should eventally get set somewhere else (a config?)
LC_AUDIT_PORT=`git config -f smsconfigfile.txt --get auditor.port`
AUDIT_HOST=`git config -f smsconfigfile.txt --get auditor.host`
AUDIT_USER=`git config -f smsconfigfile.txt --get auditor.user`
echo ""
SOCAT=$(which socat)
# BLOCK_SIZE="-b 64"
BLOCK_SIZE=""
ADDR1="tcp-l:$LC_AUDIT_PORT,reuseaddr"
ADDR2="FILE:/dev/ttyUSB0,nonblock,b9600,raw"
# ADDR2="FILE:carelink.ttyUSB0,b9600,raw"
# $ socat pty,link=$HOME/dev/vmodem0,waitslave tcp:modem-server:54321
SOCAT_ARGS="-d -d ${BLOCK_SIZE} ${ADDR1} ${ADDR2}"

TOOL="audit"
SESSION=${1-'1360553446'} # ben: what is this witchcraft?
USER=${2-'5'}
echo "$SOCAT $SOCAT_ARGS"
#auditingKey is the location, it might come from a config, eh?
dropbear_args="-i auditingKey -A"
ssh_hint="$dropbear_args -R localhost:$LC_AUDIT_PORT:localhost:$LC_AUDIT_PORT $AUDIT_USER@$AUDITHOST $TOOL $SESSION $USER"
echo "now run ssh $ssh_hint"
$SOCAT $SOCAT_ARGS &

exec ssh $ssh_hint
echo '' | nc localhost $LC_AUDIT_PORT
#####
# EOF
