#!/bin/sh
#export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:$PYTHONPATH

ADDR=`python /usr/bin/parseSMS.py | grep https |tail -1 `
LOGFILE=$LOGFILE
echo $ADDR
if [ -z ${ADDR} ] 
  then
  D=`date`
  echo no poll ${D}
  echo no poll ${D} >> $LOGFILE
  else
  D=`date`
  echo successful poll ${D} 
  echo successful poll ${D} >> $LOGFILE
  pon icon322 >> $LOGFILE
  ifconfig >> $LOGFILE
  route >> $LOGFILE
  cp /etc/master.resolv.conf /etc/resolv.conf
  ping -c2 google.com
  ping -c2 transactionalweb.com
  curl -k ${ADDR} > /home/new/smsconfigfile.txt
  poff
  cat /home/new/smsconfigfile.txt >> logfile.txt
  cat /home/new/smsconfigfile.txt
fi
